#!/bin/bash

source api

KEY=$((RANDOM % 9000 + 1000))

cpu_info=()
cpu_info+=("Architecture" "$(get_cpu_architecture)")
cpu_info+=("Model name" "$(get_cpu_name)")
cpu_info+=("Clock speed" "$(get_cpu_speed)")
cpu_info+=("Cores" "$(get_cpu_cores)")
cpu_info+=("Virtualization" "$(get_cpu_vtx)")

gpu_info=()
gpu_info+=("Brand" "$(get_gpu_brand)")
gpu_info+=("Model name" "$(get_gpu_name)")
gpu_info+=("Memory" "$(get_gpu_memory)")

ram_info=()
ram_info+=("Total memory" "$(get_total_memory)")
ram_info+=("Branded capacity" "$(get_memory_simple)")

motherboard_info=()
motherboard_info+=("Product" "$(get_product)")
motherboard_info+=("Motherboard Brand" "$(get_motherboard_brand)")
motherboard_info+=("Model" "$(get_motherboard_model)")

os_info=()
os_info+=("Name" "$(get_distro_prettyname)")
os_info+=("Distribution" "$(get_distro_name)")
os_info+=("Version" "$(get_distro_version)")
os_info+=("Computer name" "$(get_network_name)")
os_info+=("Kernel type" "$(get_kernel_name)")
os_info+=("Kernel version" "$(get_kernel_version)")
os_info+=("Desktop environment" "$(get_desktop_environment)")
os_info+=("Windowing system" "$(get_windowing_system)")

yad --plug="$KEY" --tabnum=1 --list --no-selection --column="Parameter" \
    --column="Value" --no-headers "${cpu_info[@]}" &
yad --plug="$KEY" --tabnum=2 --list --no-selection --column="Parameter" \
    --column="Value" --no-headers "${gpu_info[@]}" &
yad --plug="$KEY" --tabnum=3 --list --no-selection --column="Parameter" \
    --column="Value" --no-headers "${ram_info[@]}" &
yad --plug="$KEY" --tabnum=4 --list --no-selection --column="Parameter" \
    --column="Value" --no-headers "${motherboard_info[@]}" &

df -B1 --output=source,target,fstype,size,avail,pcent | tail -n +2 | grep "/dev/" | \
awk '{
    cmd="numfmt --to=iec --suffix=B " $4; cmd | getline total; close(cmd)
    cmd="numfmt --to=iec --suffix=B " $5; cmd | getline free; close(cmd)
    # insert a space before the unit (B, K, M, G, T)
    gsub(/([KMGT]?B)$/, " &", total)
    gsub(/([KMGT]?B)$/, " &", free)
    printf "%s\n%s\n%s\n%s\n%s\n%s\n", $1,$2,$3,total,free,$6
}' | \
yad --plug="$KEY" --tabnum=5 --list --no-selection \
    --column="Device" --column="Mountpoint" \
    --column="Type"  --column="Total" \
    --column="Free" --column="Usage:bar" &

yad --plug="$KEY" --tabnum=6 --list --no-selection --column="Parameter" \
    --column="Value" --no-headers "${os_info[@]}" &

awk '{printf "%s\n", $1}' /proc/modules | sed "s/[,-]$//" | sort |\
  yad --plug="$KEY" --tabnum=7 --text="Currently loaded kernel modules" --list --column="Name" --no-headers &

GDK_BACKEND=x11 yad --notebook --title="Systemboard - $(hostname)" --key="$KEY" --tab="CPU" --tab="GPU" \
    --tab="Memory" --tab="Motherboard" --tab="Disks" --tab="$(os_type)" --tab="Kernel" \
    --width=700 --height=500 --center --no-buttons --tab-pos=left \
    --icon="$(get_icon)" --image="$(get_icon)" --image-on-top --class="Systemboard" \
    --text="$(systemboard_title_text)"
